inference:
  input_dim : 104
  hidden_dim : 64
  checkpoint_path: '/4TBHD/ISL/CodeBase/vector_models/10kmodels'


filters:
  face_filter: [4, 13, 68, 93, 151, 175, 207, 298, 427, 454, 33, 133, 362, 263]
  pose_filter: [11, 12, 13, 14, 15, 16, 23, 24]
  lh_filter: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 20]   # [5,9,13,17] -> [26,29,32,35]
  rh_filter: [0 , 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 20]  # [5,9,13,17] -> [42,45,48,51]


seq_classifier_inference:
  checkpoint_path: '/4TBHD/ISL/CodeBase/sign_models/LSTM_hidden-size:256_num-layers:1_v3_expanded.h5'

label_mapping:
  0: 'beautiful'
  1: 'brush'
  2: 'bye'
  3: 'cook'
  4: 'dead'
  5: 'go'
  6: 'good'
  7: 'hello'
  8: 'sorry'
  9: 'thankyou'
  10: "above"
  11: "aeroplane"
  12: "bed"
  13: "below"
  14: "black"
  15: "bob"
  16: "bowl"
  17: "cat"
  18: "coat"
  19: "coffee"
  20: "conductor"
  21: "cup"
  22: "doctor"
  23: "dog"
  24: "door"
  25: "dustbin"
  26: "earmuffs"
  27: "earth"
  28: "family"
  29: "fish"
  30: "garden"
  31: "gift"
  32: "glasses"
  33: "goodmorning"
  34: "hairband"
  35: "key"
  36: "lock"
  37: "lorry"
  38: "mirror"
  39: "party"
  40: "room"
  41: "shoot"
  42: "summer"
  43: "swimming"
  44: "talk"
  45: "teacher"
  46: "thursday"
  47: "train"
  48: "tubelight"
  49: "winter"



output_dim_mapping:

  right_arm_folded: 3
  right_forearm_orientation: 4
  right_finger_closeness_to_face: 9
  right_fingers_joined: 2
  right_fingertips_orientation: 10
  right_hand_position_along_body: 4
  right_palm_position: 6
  right_elbow_orientation: 4
  left_arm_folded: 4
  left_forearm_orientation: 4
  left_elbow_orientation: 4
  left_hand_position_along_body: 5
  left_fingertips_orientation: 14
  left_palm_position: 7
  left_fingers_joined: 2
  left_fingers_closeness_to_face: 7
  hands_involved: 3
  joined_hand_orientation: 4
  relative_hand_height: 3
  hand_synchronization: 3

input_dim_mapping:

  right_arm_folded: 4
  right_forearm_orientation: 3
  right_elbow_orientation: 18
  right_hand_position_along_body: 12 # nw model
  right_fingertips_orientation: 6
  right_palm_position: 7
  right_fingers_joined: 11
  right_finger_closeness_to_face: 20
  left_arm_folded: 38 #36
  left_forearm_orientation: 18
  left_elbow_orientation: 18
  left_hand_position_along_body: 12 #11
  left_fingertips_orientation: 16
  left_palm_position: 6
  left_fingers_joined: 16
  left_fingers_closeness_to_face: 20
  hands_involved: 52 #54
  joined_hand_orientation: 52
  relative_hand_height: 52
  hand_synchronization: 52 #54

hidden_dim_mapping:

  right_arm_folded: [128,256,512,256,128]  #64
  right_forearm_orientation: [64,128,256,512,256,128,64] #64
  right_elbow_orientation: [128,128,256,512,256,128,128] #64
  right_hand_position_along_body: [128,256,512,256,128] #64
  right_fingertips_orientation: [128,256,512,256,128] #64
  right_palm_position: [128,256,512,256,128] #64
  right_fingers_joined: [512,512,512,512,512] #64
  right_finger_closeness_to_face: [256,256,512,256,256]
  left_arm_folded: [64,128,64]
  left_forearm_orientation: [64,128,64]
  left_elbow_orientation: [64,128,64]
  left_hand_position_along_body: [64,128,64]
  left_fingertips_orientation: [128,254,124]
  left_palm_position: [64,128,64]
  left_fingers_joined: [64,128,64]
  left_fingers_closeness_to_face: [64,128,64]
  hands_involved: [64,128,64]
  joined_hand_orientation: [64,128,64]
  relative_hand_height: [64,128,64]
  hand_synchronization: [64,128,64]



# The below is for non-shifted orgin

# output_dim_mapping:

#   right_arm_folded: 3
#   right_forearm_orientation: 4
#   right_finger_closeness_to_face: 9
#   right_fingers_joined: 2
#   right_fingertips_orientation: 5
#   right_hand_position_along_body: 4
#   right_palm_position: 6
#   right_elbow_orientation: 4
#   left_arm_folded: 4
#   left_forearm_orientation: 4
#   left_elbow_orientation: 4
#   left_hand_position_along_body: 5
#   left_fingertips_orientation: 13
#   left_palm_position: 7
#   left_fingers_joined: 2
#   left_fingers_closeness_to_face: 7
#   hands_involved: 3
#   joined_hand_orientation: 4
#   relative_hand_height: 3
#   hand_synchronization: 3

# input_dim_mapping:

#   right_arm_folded: 104
#   right_forearm_orientation: 104
#   right_elbow_orientation: 104
#   right_hand_position_along_body: 104
#   right_fingertips_orientation: 104
#   right_palm_position: 104
#   right_fingers_joined: 104
#   right_finger_closeness_to_face: 104
#   left_arm_folded: 36
#   left_forearm_orientation: 18
#   left_elbow_orientation: 18
#   left_hand_position_along_body: 11
#   left_fingertips_orientation: 16
#   left_palm_position: 6
#   left_fingers_joined: 16
#   left_fingers_closeness_to_face: 20
#   hands_involved: 52
#   joined_hand_orientation: 52
#   relative_hand_height: 52
#   hand_synchronization: 52

# hidden_dim_mapping:

#   right_arm_folded: 64
#   right_forearm_orientation: 64
#   right_elbow_orientation: 64
#   right_hand_position_along_body: 64
#   right_fingertips_orientation: 64
#   right_palm_position: 64
#   right_fingers_joined: 64
#   right_finger_closeness_to_face: 64
#   left_arm_folded: [64,128,64]
#   left_forearm_orientation: [64,128,64]
#   left_elbow_orientation: [64,128,64]
#   left_hand_position_along_body: [64,128,64]
#   left_fingertips_orientation: [128,254,124]
#   left_palm_position: [64,128,64]
#   left_fingers_joined: [64,128,64]
#   left_fingers_closeness_to_face: [64,128,64]
#   hands_involved: [64,128,64]
#   joined_hand_orientation: [64,128,64]
#   relative_hand_height: [64,128,64]
#   hand_synchronization: [64,128,64]


# # The below is for shifted orgin
# output_dim_mapping:

#   right_arm_folded: 3
#   right_forearm_orientation: 4
#   right_finger_closeness_to_face: 9
#   right_fingers_joined: 2
#   right_fingertips_orientation: 10
#   right_hand_position_along_body: 4
#   right_palm_position: 6
#   right_elbow_orientation: 4
#   left_arm_folded: 4
#   left_forearm_orientation: 4
#   left_elbow_orientation: 4
#   left_hand_position_along_body: 5# The below is for shifted orgin
# output_dim_mapping:

#   right_arm_folded: 3
#   right_forearm_orientation: 4
#   right_finger_closeness_to_face: 9
#   right_fingers_joined: 2
#   right_fingertips_orientation: 10
#   right_hand_position_along_body: 4
#   right_palm_position: 6
#   right_elbow_orientation: 4
#   left_arm_folded: 4
#   left_forearm_orientation: 4
#   left_elbow_orientation: 4
#   left_hand_position_along_body: 5
#   left_fingertips_orientation: 13
#   left_palm_position: 7
#   left_fingers_joined: 2
#   left_fingers_closeness_to_face: 7
#   hands_involved: 3
#   joined_hand_orientation: 4
#   relative_hand_height: 3
#   hand_synchronization: 3

# input_dim_mapping:

#   right_arm_folded: 4
#   right_forearm_orientation: 3
#   right_elbow_orientation: 18
#   right_hand_position_along_body: 10
#   right_fingertips_orientation: 6
#   right_palm_position: 7
#   right_fingers_joined: 11
#   right_finger_closeness_to_face: 20
#   left_arm_folded: 36
#   left_forearm_orientation: 18
#   left_elbow_orientation: 18
#   left_hand_position_along_body: 11
#   left_fingertips_orientation: 16
#   left_palm_position: 6
#   left_fingers_joined: 16
#   left_fingers_closeness_to_face: 20
#   hands_involved: 52
#   joined_hand_orientation: 52
#   relative_hand_height: 52
#   hand_synchronization: 52

# hidden_dim_mapping:

#   right_arm_folded: [128,256,512,256,128]  #64
#   right_forearm_orientation: [64,128,256,512,256,128,64] #64
#   right_elbow_orientation: [128,128,256,512,256,128,128] #64
#   right_hand_position_along_body: [128,256,512,256,128] #64
#   right_fingertips_orientation: [128,256,512,256,128] #64
#   right_palm_position: [128,256,512,256,128] #64
#   right_fingers_joined: [512,512,512,512,512] #64
#   right_finger_closeness_to_face: [256,256,512,256,256]
#   left_arm_folded: [64,128,64]
#   left_forearm_orientation: [64,128,64]
#   left_elbow_orientation: [64,128,64]
#   left_hand_position_along_body: [64,128,64]
#   left_fingertips_orientation: [128,254,124]
#   left_palm_position: [64,128,64]
#   left_fingers_joined: [64,128,64]
#   left_fingers_closeness_to_face: [64,128,64]
#   hands_involved: [64,128,64]
#   joined_hand_orientation: [64,128,64]
#   relative_hand_height: [64,128,64]
#   hand_synchronization: [64,128,64]

#   left_fingertips_orientation: 13
#   left_palm_position: 7
#   left_fingers_joined: 2
#   left_fingers_closeness_to_face: 7
#   hands_involved: 3
#   joined_hand_orientation: 4
#   relative_hand_height: 3
#   hand_synchronization: 3

# input_dim_mapping:

#   right_arm_folded: 4
#   right_forearm_orientation: 3
#   right_elbow_orientation: 18
#   right_hand_position_along_body: 10
#   right_fingertips_orientation: 6
#   right_palm_position: 7
#   right_fingers_joined: 11
#   right_finger_closeness_to_face: 20
#   left_arm_folded: 36
#   left_forearm_orientation: 18
#   left_elbow_orientation: 18
#   left_hand_position_along_body: 11
#   left_fingertips_orientation: 16
#   left_palm_position: 6
#   left_fingers_joined: 16
#   left_fingers_closeness_to_face: 20
#   hands_involved: 52
#   joined_hand_orientation: 52
#   relative_hand_height: 52
#   hand_synchronization: 52

# hidden_dim_mapping:

#   right_arm_folded: [128,256,512,256,128]  #64
#   right_forearm_orientation: [64,128,256,512,256,128,64] #64
#   right_elbow_orientation: [128,128,256,512,256,128,128] #64
#   right_hand_position_along_body: [128,256,512,256,128] #64
#   right_fingertips_orientation: [128,256,512,256,128] #64
#   right_palm_position: [128,256,512,256,128] #64
#   right_fingers_joined: [512,512,512,512,512] #64
#   right_finger_closeness_to_face: [256,256,512,256,256]
#   left_arm_folded: [64,128,64]
#   left_forearm_orientation: [64,128,64]
#   left_elbow_orientation: [64,128,64]
#   left_hand_position_along_body: [64,128,64]
#   left_fingertips_orientation: [128,254,124]
#   left_palm_position: [64,128,64]
#   left_fingers_joined: [64,128,64]
#   left_fingers_closeness_to_face: [64,128,64]
#   hands_involved: [64,128,64]
#   joined_hand_orientation: [64,128,64]
#   relative_hand_height: [64,128,64]
#   hand_synchronization: [64,128,64]

# filters:
#   face_filter: [4, 13, 68, 93, 151, 175, 207, 298, 427, 454, 33, 133, 362, 263]
#   pose_filter: [11, 12, 13, 14, 15, 16]
#   lh_filter: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 20]
#   rh_filter: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 20]