"""
Author: Sandeep Kumar Suresh
        EE23S059
"""


from torch.utils.data import Dataset
import torch

# def collate_fn(batch):
#     batch = [item for item in batch if item is not None]
#     return torch.utils.data.default_collate(batch)



class SequenceClassificationDataset(Dataset):

    def __init__(self, features,labels): #,dataset)



        self.modified_feat , self.modified_label = [],[]

        # self.features = dataset["feature_list"].tolist()      
        # self.labels = dataset["labels"].tolist() 
        self.features = features      
        self.labels =  labels

        # self.label_mapping = {
        #     'go': 0,
        #     'cook': 1,
        #     'thankyou': 2,
        #     'beautiful': 3,
        #     'good': 4,
        #     'dead': 5,
        #     'sorry': 6,
        #     'hello': 7,
        #     'brush': 8,
        #     'bye': 9,
        #     'summer': 10,
        #     'cup': 11,
        #     'door': 12,
        #     'room': 13,
        #     'bed': 14,
        #     'black': 15,
        #     'winter': 16,
        #     'fish': 17,
        #     'aeroplane': 18,
        #     'teacher': 19,
        #     'goodmorning': 20,
        #     'dog': 21,
        #     'mirror': 22,
        #     'doctor': 23,
        #     'train': 24,
        #     'above': 25,
        #     'shoot': 26,
        #     'bowl': 27,
        #     'cat': 28,
        #     'coffee': 29,

        # }

        # self.label_mapping = {
        #     'dustbin': 0,
        #     'earth': 1,

        #     'below': 2,
        #     'garden': 3,

        #     'coat': 4,
        
        #     }

        # self.label_mapping = {
        # 'beautiful': 0,
        # 'brush': 1,
        # 'bye': 2,
        # 'cook': 3,
        # 'dead': 4,
        # 'go': 5,
        # 'good': 6,
        # 'hello': 7,
        # 'sorry': 8,
        # 'thankyou': 9,
        # 'above': 10,
        # 'aeroplane': 11,
        # 'bed': 12,
        # 'below': 13,
        # 'black': 14,
        # 'bob': 15,
        # 'bowl': 16,
        # 'cat': 17,
        # 'coat': 18,
        # 'coffee': 19,
        # 'conductor': 20,
        # 'cup': 21,
        # 'doctor': 22,
        # 'dog': 23,
        # 'door': 24,
        # 'dustbin': 25,
        # 'earmuffs': 26,
        # 'earth': 27,
        # 'family': 28,
        # 'fish': 29,
        # 'garden': 30,
        # 'gift': 31,
        # 'glasses': 32,
        # 'goodmorning': 33,
        # 'hairband': 34,
        # 'key': 35,
        # 'lock': 36,
        # 'lorry': 37,
        # 'mirror': 38,
        # 'party': 39,
        # 'room': 40,
        # 'shoot': 41,
        # 'summer': 42,
        # 'swimming': 43,
        # 'talk': 44,
        # 'teacher': 45,
        # 'thursday': 46,
        # 'train': 47,
        # 'tubelight': 48,
        # 'winter': 49
        # }

        self.label_mapping = {
            "actor": 0,
            "adult": 1,
            "afternoon": 2,
            "alive": 3,
            "alright": 4,
            "animal": 5,
            "artist": 6,
            "attack": 7,
            "author": 8,
            "baby": 9,
            "bad": 10,
            "bag": 11,
            "ball": 12,
            "bank": 13,
            "bathroom": 14,
            "beautiful": 15,
            "bed": 16,
            "bedroom": 17,
            "bicycle": 18,
            "biglarge": 19,
            "bill": 20,
            "bird": 21,
            "black": 22,
            "blind": 23,
            "blue": 24,
            "boat": 25,
            "book": 26,
            "box": 27,
            "boy": 28,
            "brother": 29,
            "brown": 30,
            "bus": 31,
            "camera": 32,
            "car": 33,
            "card": 34,
            "cat": 35,
            "cellphone": 36,
            "chair": 37,
            "cheap": 38,
            "child": 39,
            "city": 40,
            "clean": 41,
            "clock": 42,
            "clothing": 43,
            "cold": 44,
            "colour": 45,
            "computer": 46,
            "cool": 47,
            "court": 48,
            "cow": 49,
            "crowd": 50,
            "curved": 51,
            "daughter": 52,
            "dead": 53,
            "deaf": 54,
            "death": 55,
            "deep": 56,
            "dirty": 57,
            "doctor": 58,
            "dog": 59,
            "door": 60,
            "dream": 61,
            "dress": 62,
            "dry": 63,
            "election": 64,
            "energy": 65,
            "evening": 66,
            "exercise": 67,
            "ex.monsoon": 68,
            "expensive": 69,
            "fall": 70,
            "family": 71,
            "famous": 72,
            "fan": 73,
            "fast": 74,
            "father": 75,
            "female": 76,
            "fish": 77,
            "flat": 78,
            "friday": 79,
            "friend": 80,
            "gift": 81,
            "girl": 82,
            "god": 83,
            "good": 84,
            "goodafternoon": 85,
            "goodevening": 86,
            "goodmorning": 87,
            "goodnight": 88,
            "grandfather": 89,
            "grandmother": 90,
            "green": 91,
            "grey": 92,
            "ground": 93,
            "gun": 94,
            "happy": 95,
            "hard": 96,
            "hat": 97,
            "he": 98,
            "healthy": 99,
            "heavy": 100,
            "hello": 101,
            "high": 102,
            "horse": 103,
            "hospital": 104,
            "hot": 105,
            "hour": 106,
            "house": 107,
            "howareyou": 108,
            "husband": 109,
            "i": 110,
            "india": 111,
            "it": 112,
            "job": 113,
            "key": 114,
            "king": 115,
            "kitchen": 116,
            "lamp": 117,
            "laptop": 118,
            "lawyer": 119,
            "letter": 120,
            "library": 121,
            "light": 122,
            "location": 123,
            "lock": 124,
            "long": 125,
            "loose": 126,
            "loud": 127,
            "low": 128,
            "male": 129,
            "man": 130,
            "manager": 131,
            "market": 132,
            "marriage": 133,
            "mean": 134,
            "medicine": 135,
            "minute": 136,
            "monday": 137,
            "money": 138,
            "month": 139,
            "morning": 140,
            "mother": 141,
            "mouse": 142,
            "narrow": 143,
            "neighbour": 144,
            "new": 145,
            "newspaper": 146,
            "nice": 147,
            "night": 148,
            "office": 149,
            "old": 150,
            "orange": 151,
            "page": 152,
            "paint": 153,
            "pant": 154,
            "paper": 155,
            "parent": 156,
            "park": 157,
            "patient": 158,
            "peace": 159,
            "pen": 160,
            "pencil": 161,
            "photograph": 162,
            "pink": 163,
            "plane": 164,
            "player": 165,
            "pleased": 166,
            "pocket": 167,
            "police": 168,
            "poor": 169,
            "president": 170,
            "price": 171,
            "priest": 172,
            "queen": 173,
            "quiet": 174,
            "race(ethnicity)": 175,
            "radio": 176,
            "red": 177,
            "religion": 178,
            "reporter": 179,
            "restaurant": 180,
            "rich": 181,
            "ring": 182,
            "sad": 183,
            "saturday": 184,
            "school": 185,
            "science": 186,
            "screen": 187,
            "season": 188,
            "second": 189,
            "secretary": 190,
            "shallow": 191,
            "she": 192,
            "shirt": 193,
            "shoes": 194,
            "short": 195,
            "sick": 196,
            "sign": 197,
            "sister": 198,
            "skirt": 199,
            "slow": 200,
            "smalllittle": 201,
            "soap": 202,
            "soft": 203,
            "soldier": 204,
            "son": 205,
            "sport": 206,
            "spring": 207,
            "storeorshop": 208,
            "streetorroad": 209,
            "strong": 210,
            "student": 211,
            "suit": 212,
            "summer": 213,
            "sunday": 214,
            "table": 215,
            "tall": 216,
            "teacher": 217,
            "team": 218,
            "technology": 219,
            "telephone": 220,
            "television": 221,
            "temple": 222,
            "thankyou": 223,
            "they": 224,
            "thick": 225,
            "thin": 226,
            "thursday": 227,
            "tight": 228,
            "time": 229,
            "today": 230,
            "tomorrow": 231,
            "tool": 232,
            "train": 233,
            "trainstation": 234,
            "trainticket": 235,
            "transportation": 236,
            "truck": 237,
            "t-shirt": 238,
            "tuesday": 239,
            "ugly": 240,
            "university": 241,
            "waiter": 242,
            "war": 243,
            "warm": 244,
            "we": 245,
            "weak": 246,
            "wednesday": 247,
            "week": 248,
            "wet": 249,
            "white": 250,
            "wide": 251,
            "wife": 252,
            "window": 253,
            "winter": 254,
            "woman": 255,
            "year": 256,
            "yellow": 257,
            "yesterday": 258,
            "you": 259,
            "young": 260,
            "you(plural)": 261
            }



        # self.label_mapping = {
        #             'dustbin': 0,
        #             'family': 1,
        #             'tubelight': 2,
        #             'earth': 3,
        #             'hairband': 4,
        #             'earmuffs': 5,
        #             'below': 6,
        #             'garden': 7,
        #             'gift': 8,
        #             'lock': 9,
        #             'talk': 10,
        #             'key': 11,
        #             'conductor': 12,
        #             'glasses': 13,
        #             'lorry': 14,
        #             'thursday': 15,
        #             'bob': 16,
        #             'party': 17,
        #             'coat': 18,
        #             'swimming': 19
        #         }


        # self.label_mapping = {
        #             'dustbin': 0,   
        #             'coat': 1,

        #             'swimming': 2,
        #             'key': 3,

        #             'lock': 4
        #         }

        # self.label_mapping = {
        #             'adult': 0,   
        #             'blue': 1,

        #             'baby': 2,
        #             'bicycle': 3,

        #             'i': 4
        #         }

        # self.label_mapping = {
        #     "adult": 0,
        #     "alright": 1,
        #     "animal": 2,
        #     "baby": 3,
        #     "bad": 4,
        #     "bank": 5,
        #     "bicycle": 6,
        #     "biglarge": 7,
        #     "bird": 8,
        #     "black": 9,
        #     "blue": 10,
        #     "boat": 11,
        #     "boy": 12,
        #     "brother": 13,
        #     "brown": 14,
        #     "bus": 15,
        #     "car": 16,
        #     "cat": 17,
        #     "child": 18,
        #     "city": 19,
        #     "clothing": 20,
        #     "cold": 21,
        #     "colour": 22,
        #     "cool": 23,
        #     "court": 24,
        #     "cow": 25,
        #     "crowd": 26,
        #     "daughter": 27,
        #     "dog": 28,
        #     "dress": 29,
        #     "dry": 30,
        #     "fast": 31,
        #     "father": 32,
        #     "fish": 33,
        #     "friend": 34,
        #     "girl": 35,
        #     "good": 36,
        #     "goodafternoon": 37,
        #     "goodevening": 38,
        #     "goodmorning": 39,
        #     "goodnight": 40,
        #     "green": 41,
        #     "grey": 42,
        #     "ground": 43,
        #     "happy": 44,
        #     "hat": 45,
        #     "he": 46,
        #     "healthy": 47,
        #     "hello": 48,
        #     "horse": 49,
        #     "hospital": 50,
        #     "hot": 51,
        #     "house": 52,
        #     "howareyou": 53,
        #     "husband": 54,
        #     "i": 55,
        #     "india": 56,
        #     "it": 57,
        #     "king": 58,
        #     "library": 59,
        #     "location": 60,
        #     "long": 61,
        #     "loud": 62,
        #     "man": 63,
        #     "market": 64,
        #     "mother": 65,
        #     "mouse": 66,
        #     "narrow": 67,
        #     "neighbour": 68,
        #     "new": 69,
        #     "office": 70,
        #     "old": 71,
        #     "orange": 72,
        #     "pant": 73,
        #     "parent": 74,
        #     "park": 75,
        #     "pink": 76,
        #     "plane": 77,
        #     "player": 78,
        #     "pleased": 79,
        #     "pocket": 80,
        #     "president": 81,
        #     "queen": 82,
        #     "quiet": 83,
        #     "red": 84,
        #     "restaurant": 85,
        #     "school": 86,
        #     "she": 87,
        #     "shirt": 88,
        #     "shoes": 89,
        #     "short": 90,
        #     "sick": 91,
        #     "sister": 92,
        #     "skirt": 93,
        #     "slow": 94,
        #     "smalllittle": 95,
        #     "son": 96,
        #     "storeorshop": 97,
        #     "streetorroad": 98,
        #     "suit": 99,
        #     "tall": 100,
        #     "temple": 101,
        #     "thankyou": 102,
        #     "they": 103,
        #     "train": 104,
        #     "trainstation": 105,
        #     "trainticket": 106,
        #     "transportation": 107,
        #     "truck": 108,
        #     "t-shirt": 109,
        #     "university": 110,
        #     "warm": 111,
        #     "we": 112,
        #     "wet": 113,
        #     "white": 114,
        #     "wide": 115,
        #     "wife": 116,
        #     "woman": 117,
        #     "yellow": 118,
        #     "you": 119,
        #     "young": 120,
        #     "you(plural)": 121
        # }

        # self.label_mapping = {
        #     "bank": 0,
        #     "biglarge": 1,
        #     "bird": 2,
        #     "black": 3,
        #     "boy": 4,
        #     "brother": 5,
        #     "car": 6,
        #     "cellphone": 7,
        #     "court": 8,
        #     "cow": 9,
        #     "death": 10,
        #     "dog": 11,
        #     "dry": 12,
        #     "election": 13,
        #     "fall": 14,
        #     "fan": 15,
        #     "father": 16,
        #     "girl": 17,
        #     "good": 18,
        #     "goodmorning": 19,
        #     "happy": 20,
        #     "hat": 21,
        #     "hello": 22,
        #     "hot": 23,
        #     "house": 24,
        #     "i": 25,
        #     "it": 26,
        #     "long": 27,
        #     "loud": 28,
        #     "monday": 29,
        #     "new": 30,
        #     "paint": 31,
        #     "pen": 32,
        #     "priest": 33,
        #     "quiet": 34,
        #     "red": 35,
        #     "shoes": 36,
        #     "short": 37,
        #     "smalllittle": 38,
        #     "storeorshop": 39,
        #     "summer": 40,
        #     "teacher": 41,
        #     "thankyou": 42,
        #     "time": 43,
        #     "trainticket": 44,
        #     "t-shirt": 45,
        #     "white": 46,
        #     "window": 47,
        #     "year": 48,
        #     "you(plural)": 49
        # }




        for feat,label in zip(self.features,self.labels):
            # print(feat)
            self.modified_feat.append(torch.tensor(feat,dtype = torch.float))
            self.modified_label.append(self.label_mapping.get(label))



    
    def __len__(self):
        """
        Note: We are getting the length of the list
        """
        return len(self.modified_label)

    
    def __getitem__(self, idx):
                

        data = self.modified_feat[idx]
        label = self.modified_label[idx]
        if data is None or label is None:
            print(f"Invalid data or label at index {idx}")        
        
        return self.modified_feat[idx],self.modified_label[idx]

